package com.pinyougou.mapper;

import com.pinyougou.pojo.TbAreas;
import com.pinyougou.pojo.TbAreasExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbAreasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int countByExample(TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int deleteByExample(TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int insert(TbAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int insertSelective(TbAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    List<TbAreas> selectByExample(TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    TbAreas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbAreas record, @Param("example") TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int updateByExample(@Param("record") TbAreas record, @Param("example") TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int updateByPrimaryKeySelective(TbAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbggenerated Fri Dec 21 12:39:48 CST 2018
     */
    int updateByPrimaryKey(TbAreas record);
}